#!/bin/bash
rsync -rv "rsync://mirrors.tuna.tsinghua.edu.cn/archlinux/iso/latest/arch" .
VERSION="$(curl -sL https://mirrors.tuna.tsinghua.edu.cn/archlinux/iso/ \
    | sed "/.*\>/i\n" \
    | grep -Eo "[0-9]{4}.[0-9]{2}.01" \
    | uniq \
    | tail -1)"
sed -Ei "s/[0-9]{4}.[0-9]{2}.01/$VERSION/g" ../archlinux.ipxe
